apply plugin: 'com.android.application'

android {
    namespace 'com.demo.jewelcoloring'
    compileSdk 36
    defaultConfig {
        applicationId 'com.demo.jewelcoloring'
        minSdk 21
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }
    signingConfigs {
        release {
            storeFile file('D:/Creator/3.8.8/resources/tools/keystore/debug.keystore')
            storePassword '123456'
            keyAlias 'debug_keystore'
            keyPassword '123456'
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}